=== Stiffly/TacticalZ/resources/Schema/Components/Animation.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:t="types">
	<xs:import schemaLocation="../Types.xsd" namespace="types"/>

	<xs:complexType name="BlendEnum" mixed="true">
		<xs:complexContent>
			<xs:extension base="t:enum">
				<xs:choice>
					<xs:element name="Additive" type="xs:integer" fixed="0" minOccurs="0"/>
					<xs:element name="Blend" type="xs:integer" fixed="1" minOccurs="0"/>
					<xs:element name="Override" type="xs:integer" fixed="2" minOccurs="0"/>
				</xs:choice>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>


	<xs:element name="Animation">
		<xs:complexType>
			<xs:all>
				<xs:element name="AnimationName1" type="t:string" minOccurs="0"/>
				<xs:element name="BlendType1" type="BlendEnum" minOccurs="0"/>
				<xs:element name="Level1" type="t:int" minOccurs="0"/>
				<xs:element name="Weight1" type="t:double" minOccurs="0"/>
				<xs:element name="Time1" type="t:double" minOccurs="0"/>
				<xs:element name="Speed1" type="t:double" minOccurs="0"/>
				<xs:element name="Loop1" type="t:bool" minOccurs="0"/>

				<xs:element name="AnimationName2" type="t:string" minOccurs="0"/>
				<xs:element name="BlendType2" type="BlendEnum" minOccurs="0"/>
				<xs:element name="Level2" type="t:int" minOccurs="0"/>
				<xs:element name="Weight2" type="t:double" minOccurs="0"/>
				<xs:element name="Time2" type="t:double" minOccurs="0"/>
				<xs:element name="Speed2" type="t:double" minOccurs="0"/>
				<xs:element name="Loop2" type="t:bool" minOccurs="0"/>

				<xs:element name="AnimationName3" type="t:string" minOccurs="0"/>
				<xs:element name="BlendType3" type="BlendEnum" minOccurs="0"/>
				<xs:element name="Level3" type="t:int" minOccurs="0"/>
				<xs:element name="Weight3" type="t:double" minOccurs="0"/>
				<xs:element name="Time3" type="t:double" minOccurs="0"/>
				<xs:element name="Speed3" type="t:double" minOccurs="0"/>
				<xs:element name="Loop3" type="t:bool" minOccurs="0"/>
			</xs:all>
			<xs:attribute name="replicated" type="xs:boolean" fixed="true"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Stiffly/TacticalZ/resources/Schema/Components/Animation.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<Animation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Animation.xsd">
	<AnimationName1></AnimationName1>
	<BlendType1><Blend/></BlendType1>
	<Level1>0</Level1>
	<Weight1>1.0</Weight1>
	<Time1>0</Time1>
	<Speed1>0</Speed1>
	<Loop1>true</Loop1>
	<AnimationName2></AnimationName2>
	<BlendType2><Blend/></BlendType2>
	<Level2>0</Level2>
	<Weight2>1.0</Weight2>
	<Time2>0</Time2>
	<Speed2>0</Speed2>
	<Loop2>true</Loop2>
	<AnimationName3></AnimationName3>
	<BlendType3><Blend/></BlendType3>
	<Level3>0</Level3>
	<Weight3>1.0</Weight3>
	<Time3>0</Time3>
	<Speed3>0</Speed3>
	<Loop3>true</Loop3>
</Animation>
