=== Stiffly/TacticalZ/resources/Schema/Components/AssaultWeapon.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:t="types">
	<xs:import schemaLocation="../Types.xsd" namespace="types"/>
	<xs:include schemaLocation="../Types/WeaponSlotEnum.xsd"/>

	<xs:element name="AssaultWeapon">
		<xs:complexType>
			<xs:all>
				<xs:element name="Slot" type="WeaponSlotEnum" minOccurs="0"/>
				<xs:element name="MagazineAmmo" type="t:int" minOccurs="0">
					<xs:annotation><xs:documentation>Ammo currently loaded into the magazine</xs:documentation></xs:annotation>
				</xs:element>
				<xs:element name="MagazineSize" type="t:int" minOccurs="0">
									<xs:annotation><xs:documentation>Max number of rounds in a magazine</xs:documentation></xs:annotation>
				</xs:element>
				<xs:element name="Ammo" type="t:int" minOccurs="0">
									<xs:annotation><xs:documentation>Current ammo carried</xs:documentation></xs:annotation>
				</xs:element>
				<xs:element name="MaxAmmo" type="t:int" minOccurs="0">
									<xs:annotation><xs:documentation>Maximum ammo able to be carried</xs:documentation></xs:annotation>
				</xs:element>
				<xs:element name="BaseDamage" type="t:double" minOccurs="0"/>
				<xs:element name="SpreadAngle" type="t:float" minOccurs="0">
					<xs:annotation><xs:documentation>Spread angle in radians</xs:documentation></xs:annotation>
				</xs:element>
				<xs:element name="MaxTravelAngle" type="t:float" minOccurs="0">
					<xs:annotation><xs:documentation>Maximum vertical aim travel angle in radians</xs:documentation></xs:annotation>
				</xs:element>
				<xs:element name="RPM" type="t:double" minOccurs="0">
					<xs:annotation><xs:documentation>Rate of fire in rounds per minute</xs:documentation></xs:annotation>
				</xs:element>
				<xs:element name="ViewPunch" type="t:float" minOccurs="0">
					<xs:annotation><xs:documentation>View punch in radians for each shell fired</xs:documentation></xs:annotation>
				</xs:element>
				<xs:element name="ViewReturnSpeed" type="t:float" minOccurs="0">
					<xs:annotation><xs:documentation>The speed in radians per second the view returns to its original position after being punched</xs:documentation></xs:annotation>
				</xs:element>
				<xs:element name="ReloadTime" type="t:double" minOccurs="0">
					<xs:annotation><xs:documentation>Time it takes to load ONE SHELL into the weapon in seconds</xs:documentation></xs:annotation>
				</xs:element>
				<xs:element name="EquipTime" type="t:double" minOccurs="0">
					<xs:annotation><xs:documentation>Time it takes from selecting the weapon until it's ready to fire</xs:documentation></xs:annotation>
				</xs:element>
				<xs:element name="TriggerHeld" type="t:bool" minOccurs="0"/>
				<xs:element name="FireCooldown" type="t:double" minOccurs="0"/>
				<xs:element name="IsReloading" type="t:bool" minOccurs="0"/>
				<xs:element name="ReloadTimer" type="t:double" minOccurs="0"/>
				<xs:element name="CurrentTravel" type="t:float" minOccurs="0"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Stiffly/TacticalZ/resources/Schema/Components/AssaultWeapon.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<AssaultWeapon xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="AssaultWeapon.xsd">
	<Slot><Primary/></Slot>
	<MagazineAmmo>32</MagazineAmmo>
	<MagazineSize>32</MagazineSize>
	<Ammo>320</Ammo>
	<MaxAmmo>320</MaxAmmo>
	<BaseDamage>15</BaseDamage>
	<SpreadAngle>0.174533</SpreadAngle> <!-- 0.174533 = 10 degrees -->
	<MaxTravelAngle>0.10</MaxTravelAngle> <!-- 0.174533 = 10 degrees -->
	<RPM>420</RPM>
	<ViewPunch>0.03</ViewPunch>
	<ViewReturnSpeed>0.18</ViewReturnSpeed>
	<ReloadTime>2</ReloadTime>
	<EquipTime>0.5</EquipTime>
	<TriggerHeld>false</TriggerHeld>
	<FireCooldown>0</FireCooldown>
	<IsReloading>false</IsReloading>
	<ReloadTimer>0</ReloadTimer>
	<CurrentTravel>0</CurrentTravel>
</AssaultWeapon>
